apiVersion: v1
kind: ConfigMap
metadata:
  name: system
  namespace: substratus
data:
  CLOUD: aws
  CLUSTER_NAME: substratus # must be set by kustomize
  PRINCIPAL: substratus # must be set by kustomize
  AWS_ACCOUNT_ID: 123456789012 # must be set by kustomize
