# Adds namespace to all resources.
namespace: substratus

# Labels to add to all resources and selectors.
#labels:
#- includeSelectors: true
#  pairs:
#    someName: someValue

resources:
  - ./namespace.yaml
  - ./config.yaml
  - ../crd
  - ../rbac
  - ../manager

patches:
  - path: manager_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
